### ISSUE TITLE
error on first attemp

### ISSUE THREAD

**Issue by snapo** [gnuarmeclipse/build-scripts#1]
Hi first of all already thank you for creating this script.... but i have an issue getting it running.

`
snapo@rocco:~/Downloads$ ./build-qemu.sh --all

Using "/home/snapo/Work/qemu" as Work folder...
Script "./build-qemu.sh" started at Son Mär  6 18:47:06 CET 2016.

Running on Ubuntu 64-bits.

Checking host curl...
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Checking host git...
git version 1.9.1

Checking Docker...
Docker version 1.10.2, build c3959b1
Checking host automake...
automake (GNU automake) 1.14.1
Checking host patch...
GNU patch 2.7.1
Checking host tar...
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Checking host unzip...
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
snapo@rocco:~/Downloads$

`

I was able to download all docker images with preload-images  but after that... ... i have no clue at the moment.. im still investigating. ( Ubuntu 14.04 LTS Server )

**Comment by ilg-ul** [comment]
add a -x when starting the script, to see how the commands are invoked

I run the script on Mac, it might be something different on your Ubuntu

**Comment by snapo** [comment]
Wow.... that was crazy fast answer ;=)


```
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
+ echo 'Checking host unzip...'
Checking host unzip...
+ unzip
+ grep UnZip
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
+ case "${ACTION}" in
+ '[' '!' -d /home/snapo/Work/qemu/gnuarmeclipse-qemu.git ']'
+ source /home/snapo/Work/qemu/scripts/build-helper.sh --get-git-head
++ '[' 1 -gt 0 ']'
++ case "$1" in
++ cd /home/snapo/Work/qemu/gnuarmeclipse-qemu.git
+++ git symbolic-ref -q --short HEAD
++ GIT_HEAD=gnuarmeclipse
++ shift
++ '[' 0 -gt 0 ']'
+ source /home/snapo/Work/qemu/scripts/build-helper.sh --get-current-date
++ '[' 1 -gt 0 ']'
++ case "$1" in
+++ date -u +%Y%m%d%H%M
++ DISTRIBUTION_FILE_DATE=201603061753
++ shift
++ '[' 0 -gt 0 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/zlib-1.2.8.tar.gz ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/libpng-1.6.17.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/libpng-1.6.17 ']'
+ cd /home/snapo/Work/qemu
+ tar -xzvf /home/snapo/Work/qemu/download/libpng-1.6.17.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
snapo@rocco:~/Downloads$
```

**Comment by snapo** [comment]
saw the problem.... libpng changed version... download is the HTML ;=)

**Comment by ilg-ul** [comment]
looks like the libpng was not downloaded properly

**Comment by snapo** [comment]
http://downloads.sourceforge.net/project/libpng/libpng16/older-releases/1.6.17/libpng-1.6.17.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Flibpng%2Ffiles%2Flibpng16%2Folder-releases%2F1.6.17%2F&ts=1457287179&use_mirror=freefr

i did temporary use this address for the download... worked


second problem is 
http://cpansearch.perl.org/src/JTPALMER/Alien-SDL-1.445_2/patches/SDL_image-1.2.10-libpng15.patch

this patch is somehow not downloaded... did download it now manualy.

thanks already for the help...

**Comment by snapo** [comment]
Sorry that i am stuck again.... 

`MACPORTS_FOLDER="${MACPORTS_FOLDER}"`

Is this a path variable on your system? because i cant find a variable in the script referencing or setting this variable and the script crashes because the variable is not found (path)

Best regards

**Comment by ilg-ul** [comment]
this is a Mac only issue, you can skip it.

**Comment by snapo** [comment]
Am really sorry but im still hanging at the mac ports folder and can not figure out where / why it hangs :-(

```
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
+ case "${ACTION}" in
+ '[' '!' -d /home/snapo/Work/qemu/gnuarmeclipse-qemu.git ']'
+ source /home/snapo/Work/qemu/scripts/build-helper.sh --get-git-head
++ '[' 1 -gt 0 ']'
++ case "$1" in
++ cd /home/snapo/Work/qemu/gnuarmeclipse-qemu.git
+++ git symbolic-ref -q --short HEAD
++ GIT_HEAD=gnuarmeclipse-dev
++ shift
++ '[' 0 -gt 0 ']'
+ source /home/snapo/Work/qemu/scripts/build-helper.sh --get-current-date
++ '[' 1 -gt 0 ']'
++ case "$1" in
+++ date -u +%Y%m%d%H%M
++ DISTRIBUTION_FILE_DATE=201603072303
++ shift
++ '[' 0 -gt 0 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/zlib-1.2.8.tar.gz ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/libpng-1.6.17.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/libpng-1.6.17 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/jpegsrc.v9a.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/jpeg-9a ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/SDL-1.2.15.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/SDL-1.2.15 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/SDL_image-1.2.10.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/SDL_image-1.2.10 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/libffi-3.2.1.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/libffi-3.2.1 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/libiconv-1.14.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/libiconv-1.14 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/gettext-0.19.5.1.tar.xz ']'
+ '[' '!' -d /home/snapo/Work/qemu/gettext-0.19.5.1 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/glib-2.44.1.tar.xz ']'
+ '[' '!' -d /home/snapo/Work/qemu/glib-2.44.1 ']'
+ '[' '!' -f /home/snapo/Work/qemu/download/pixman-0.32.6.tar.gz ']'
+ '[' '!' -d /home/snapo/Work/qemu/pixman-0.32.6 ']'
+ script_name=build.sh
+ script_file=/home/snapo/Work/qemu/scripts/build.sh
+ rm -f /home/snapo/Work/qemu/scripts/build.sh
++ dirname /home/snapo/Work/qemu/scripts/build.sh
+ mkdir -p /home/snapo/Work/qemu/scripts
+ touch /home/snapo/Work/qemu/scripts/build.sh
+ cat
./build-qemu.sh: line 716: MACPORTS_FOLDER: unbound variable
```

Would you mind to give me a hint where to look next? because the script breaks (Ubuntu 14.04 LTS)

**Comment by ilg-ul** [comment]
I just pushed a new script, try it. but, as I said, MACPORTS_FOLDER is used only on Mac.

**Comment by snapo** [comment]
its now working... i made a small pull request to prevent an error because of the missing md5 files...

Thanks again

Now im gonna analyze the build errors for Win32 ;=)
